### ISSUE TITLE
Proposal: Adding sensor_msgs/JointState publisher

### ISSUE THREAD

**Issue by OkkeHendriks** [arebgun/dynamixel_motor#34]
When using the [robot_state_publisher](http://wiki.ros.org/robot_state_publisher) (which is used frequently to publish the TFs of a robot) one needs  joint states as `sensor_msgs JointState`. I created a package based on [this](http://ros-by-example.googlecode.com/svn/trunk/rbx_vol_1/rbx1_dynamixels/nodes/dynamixel_joint_state_publisher.py) code, which republishes the `dynamixel JointState` messages as `sensor_msgs JointState` messages.

This package can be found here:
https://github.com/RobotRose/dynamixel_joint_state_publisher

It may be a good idea to integrate this package into dynamixel_motor?
Or it may be a better solution to do the publishing of `sensor_msgs JointState` directly (in parallel to the dynamixel messages)?

**Comment by 130s** [comment]
I suggest you can join the discussion in the open PR https://github.com/arebgun/dynamixel_motor/pull/27. 
I close this, but please reopen if you think that PR is different from what you suggest.
