### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by 130s** [arebgun/dynamixel_motor#39]
A user (Win7, VMWare Player. Tried both Hydro on 12.04 and Indigo on 14.04) keeps seeing the following.

```
$ rosrun dynamixel_driver change_id.py -p /dev/ttyUSB0 1 2 3 4
:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 20: ordinal not in range(128)
```

We managed to find that rebooting host OS resolves this. But it'd be nicer if we know a solution to this.

**Comment by k-okada** [comment]
please run with ipython and identify which line did this error occurs
