### ISSUE TITLE
No documentation about usage of JointTrajectoryActionController

### ISSUE THREAD

**Issue by HWiese1980** [arebgun/dynamixel_motor#5]
I couldn't find any documentation about how to use the JointTrajectoryActionController. The class would most likely be exactly what I need but I can't for the life of me figure out how to use it because I haven't been able to find any examples or tutorials, yet. Or shouldn't it be used in its current state?

**Comment by socrob** [comment]
The links are broken but you can find the code in here: 

https://code.google.com/archive/p/ua-ros-pkg/source/default/source
