### ISSUE TITLE
Install error, unmet dependencies

### ISSUE THREAD

**Issue by Shawnnn** [arebgun/dynamixel_motor#74]
What it really means? How to solve? Thanks
> shawn@evashawn:~/catkin_ws$ sudo apt-get install ros-indigo-dynamixel-motor
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> You might want to run 'apt-get -f install' to correct these:
> The following packages have unmet dependencies:
>  ros-indigo-dynamixel-motor : Depends: ros-indigo-dynamixel-controllers but it is not going to be installed
>                               Depends: ros-indigo-dynamixel-driver but it is not going to be installed
>                               Depends: ros-indigo-dynamixel-msgs but it is not going to be installed
>                               Depends: ros-indigo-dynamixel-tutorials but it is not going to be installed
>  ros-indigo-ur-kinematics : Depends: ros-indigo-moveit-kinematics but it is not going to be installed
> E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

**Comment by 130s** [comment]
The error you got seems to be unrelated to this repo. I bet you'd get better response at http://answers.ros.org/
